export enum PagamentoStatus {
  AGUARDANDO_PAGAMENTO = "AGUARDANDO_PAGAMENTO",
  PAGAMENTO_APROVADO = "PAGAMENTO_APROVADO",
  PAGAMENTO_REJEITADO = "PAGAMENTO_REJEITADO",
  PAGAMENTO_REEMBOLSADO = "PAGAMENTO_REEMBOLSADO",
}
